channels:
  - conda-forge
conda:
  channel_priority: strict
dependencies:
  - conda-forge::numpy
  - conda-forge::pip
  - conda-forge::python=3.9
  - arviz
  - seaborn
  - pandas
  - h5py
  - scipy
  - tqdm
  - qnm
  - pytables
  - pip:
      - matplotlib
